export const data = JSON.parse("{\"key\":\"v-fffb8e28\",\"path\":\"/guide/\",\"title\":\"指南\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"指南\",\"icon\":\"lightbulb\",\"description\":\"服务 服务 ---------------------------------- chat (chat.md) favor (user.md) video (video.md) relation (relation.md) user (user.md) GopherTok 第六届字节跳动青训营大项目作品，使用go-zero搭建的微服务项目，由gophe...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/guide/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"GopherTok\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"指南\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"服务 服务 ---------------------------------- chat (chat.md) favor (user.md) video (video.md) relation (relation.md) user (user.md) GopherTok 第六届字节跳动青训营大项目作品，使用go-zero搭建的微服务项目，由gophe...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Gopher\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"指南\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Gopher\\\",\\\"url\\\":\\\"https://github.com/GophersTeam\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"服务\",\"slug\":\"服务\",\"link\":\"#服务\",\"children\":[]},{\"level\":2,\"title\":\"GopherTok\",\"slug\":\"gophertok\",\"link\":\"#gophertok\",\"children\":[{\"level\":3,\"title\":\"架构\",\"slug\":\"架构\",\"link\":\"#架构\",\"children\":[]},{\"level\":3,\"title\":\"🚀技术栈\",\"slug\":\"🚀技术栈\",\"link\":\"#🚀技术栈\",\"children\":[]},{\"level\":3,\"title\":\"高可用\",\"slug\":\"高可用\",\"link\":\"#高可用\",\"children\":[]},{\"level\":3,\"title\":\"高并发\",\"slug\":\"高并发\",\"link\":\"#高并发\",\"children\":[]},{\"level\":3,\"title\":\"高性能\",\"slug\":\"高性能\",\"link\":\"#高性能\",\"children\":[]},{\"level\":3,\"title\":\"配置中心和服务发现、注册中心\",\"slug\":\"配置中心和服务发现、注册中心\",\"link\":\"#配置中心和服务发现、注册中心\",\"children\":[]},{\"level\":3,\"title\":\"链路追踪\",\"slug\":\"链路追踪\",\"link\":\"#链路追踪\",\"children\":[]},{\"level\":3,\"title\":\"日志搜集\",\"slug\":\"日志搜集\",\"link\":\"#日志搜集\",\"children\":[]},{\"level\":3,\"title\":\"监控\",\"slug\":\"监控\",\"link\":\"#监控\",\"children\":[]},{\"level\":3,\"title\":\"网关\",\"slug\":\"网关\",\"link\":\"#网关\",\"children\":[]},{\"level\":3,\"title\":\"CI/CD\",\"slug\":\"ci-cd\",\"link\":\"#ci-cd\",\"children\":[]},{\"level\":3,\"title\":\"感谢\",\"slug\":\"感谢\",\"link\":\"#感谢\",\"children\":[]},{\"level\":3,\"title\":\"许可证\",\"slug\":\"许可证\",\"link\":\"#许可证\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.52,\"words\":756},\"filePathRelative\":\"guide/README.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
